# Generated by Django 3.2.6 on 2021-08-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Completed')], max_length=50),
        ),
    ]
